export const NICHE_SUBREDDITS: Record<string, string[]> = {
  fitness: ['Fitness', 'bodyweightfitness', 'loseit', 'gainit', 'running', 'weightlifting'],
  health: ['health', 'nutrition', 'sleep', 'chronicpain', 'AskDoctorSmeeee'],
  saas: ['SaaS', 'startups', 'microsaas', 'EntrepreneurRideAlong', 'indiehackers'],
  startup: ['startups', 'Entrepreneur', 'EntrepreneurRideAlong', 'smallbusiness', 'SaaS'],
  freelancing: ['freelance', 'Upwork', 'freelanceWriters', 'forhire', 'digitalnomad'],
  'remote work': ['remotework', 'digitalnomad', 'WorkOnline', 'freelance', 'telecommuting'],
  parenting: ['Parenting', 'beyondthebump', 'NewParents', 'toddlers', 'SingleParents'],
  cooking: ['Cooking', 'MealPrepSunday', 'budgetfood', 'EatCheapAndHealthy', 'nutrition'],
  finance: ['personalfinance', 'financialindependence', 'investing', 'povertyfinance', 'frugal'],
  investing: ['investing', 'stocks', 'dividends', 'Bogleheads', 'personalfinance'],
  crypto: ['CryptoCurrency', 'Bitcoin', 'ethereum', 'CryptoMarkets', 'defi'],
  gaming: ['gaming', 'gamedev', 'indiegaming', 'patientgamers', 'pcgaming'],
  travel: ['travel', 'solotravel', 'digitalnomad', 'backpacking', 'Flights'],
  dating: ['dating', 'dating_advice', 'OnlineDating', 'Tinder', 'relationship_advice'],
  relationships: ['relationship_advice', 'relationships', 'Marriage', 'dating_advice', 'BreakUps'],
  'mental health': ['mentalhealth', 'depression', 'Anxiety', 'therapy', 'ADHD'],
  adhd: ['ADHD', 'ADHDmemes', 'adhdwomen', 'productivity', 'mentalhealth'],
  productivity: ['productivity', 'getdisciplined', 'selfimprovement', 'ADHD', 'nosurf'],
  education: ['learnprogramming', 'college', 'GetStudying', 'Teachers', 'StudentLoans'],
  programming: ['learnprogramming', 'webdev', 'cscareerquestions', 'programming', 'javascript'],
  'web dev': ['webdev', 'learnprogramming', 'javascript', 'reactjs', 'Frontend'],
  javascript: ['javascript', 'reactjs', 'node', 'webdev', 'typescript'],
  python: ['learnpython', 'Python', 'django', 'MachineLearning', 'datascience'],
  'machine learning': ['MachineLearning', 'learnmachinelearning', 'datascience', 'LocalLLaMA', 'artificial'],
  ai: ['artificial', 'MachineLearning', 'LocalLLaMA', 'ChatGPT', 'singularity'],
  cybersecurity: ['netsec', 'cybersecurity', 'hacking', 'AskNetsec', 'Malware'],
  'home improvement': ['DIY', 'HomeImprovement', 'HomeDecorating', 'IKEA', 'malelivingspace'],
  pets: ['dogs', 'cats', 'puppy101', 'Pets', 'AskVet'],
  dogs: ['dogs', 'DogCare', 'puppy101', 'dogadvice', 'reactivedogs'],
  cats: ['cats', 'CatAdvice', 'AskVet', 'felinebehavior'],
  photography: ['photography', 'photocritique', 'AskPhotography', 'analog', 'weddingphotography'],
  writing: ['writing', 'worldbuilding', 'fantasywriters', 'screenwriting', 'freelanceWriters'],
  marketing: ['marketing', 'digital_marketing', 'socialmedia', 'SEO', 'PPC'],
  seo: ['SEO', 'bigseo', 'juststart', 'digital_marketing', 'blogging'],
  ecommerce: ['ecommerce', 'shopify', 'FulfillmentByAmazon', 'dropship', 'AmazonSeller'],
  dropshipping: ['dropship', 'dropshipping', 'ecommerce', 'AmazonSeller', 'shopify'],
  'real estate': ['realestateinvesting', 'RealEstate', 'FirstTimeHomeBuyer', 'landlord', 'personalfinance'],
  diet: ['loseit', 'keto', 'intermittentfasting', 'vegan', 'EatCheapAndHealthy'],
  keto: ['keto', 'xxketo', 'ketoscience', 'loseit', 'Paleo'],
  vegan: ['vegan', 'PlantBasedDiet', 'veganrecipes', 'vegetarian'],
  sleep: ['sleep', 'insomnia', 'polyphasic', 'sleephackers'],
  anxiety: ['Anxiety', 'socialanxiety', 'OCD', 'mentalhealth', 'therapy'],
  depression: ['depression', 'depression_help', 'mentalhealth', 'therapy', 'bipolar'],
  career: ['cscareerquestions', 'jobs', 'Career', 'careerguidance', 'resumes'],
  'job hunting': ['jobs', 'resumes', 'interviews', 'Career', 'cscareerquestions'],
  design: ['graphic_design', 'UI_Design', 'web_design', 'userexperience', 'logo'],
  ux: ['userexperience', 'UXDesign', 'UI_Design', 'HCI', 'webdesign'],
  youtube: ['NewTubers', 'youtube', 'youtubers', 'ContentCreators', 'videography'],
  'content creation': ['NewTubers', 'youtube', 'ContentCreators', 'Instagram', 'socialmedia'],
  music: ['WeAreTheMusicMakers', 'edmproduction', 'singing', 'Guitar', 'piano'],
  business: ['Entrepreneur', 'smallbusiness', 'startups', 'AskBusiness', 'business'],
  legal: ['legaladvice', 'law', 'personalfinance', 'tax', 'smallbusiness'],
  tax: ['tax', 'personalfinance', 'legaladvice', 'Accounting', 'taxpros'],
  insurance: ['Insurance', 'HealthInsurance', 'personalfinance', 'legaladvice'],
  shopify: ['shopify', 'ecommerce', 'dropship', 'AmazonSeller', 'Entrepreneur'],
};

const ALIASES: Record<string, string> = {
  gym: 'fitness',
  workout: 'fitness',
  exercise: 'fitness',
  'weight loss': 'diet',
  tech: 'programming',
  code: 'programming',
  coding: 'programming',
  developer: 'programming',
  software: 'programming',
  'web development': 'web dev',
  react: 'javascript',
  vue: 'javascript',
  'node.js': 'javascript',
  ml: 'machine learning',
  llm: 'ai',
  gpt: 'ai',
  'artificial intelligence': 'ai',
  security: 'cybersecurity',
  hacking: 'cybersecurity',
  house: 'home improvement',
  renovation: 'home improvement',
  dog: 'dogs',
  cat: 'cats',
  photo: 'photography',
  'content creator': 'content creation',
  instagram: 'content creation',
  tiktok: 'content creation',
  amazon: 'ecommerce',
  'job search': 'job hunting',
  resume: 'job hunting',
  interview: 'job hunting',
  'ux design': 'ux',
  'ui design': 'ux',
  'social media': 'marketing',
  blog: 'seo',
  blogging: 'seo',
  'real estate investing': 'real estate',
  landlord: 'real estate',
  housing: 'real estate',
};

export function findStaticSubreddits(niche: string): string[] {
  const q = niche.toLowerCase().trim();
  if (NICHE_SUBREDDITS[q]) return NICHE_SUBREDDITS[q];
  const aliasKey = ALIASES[q];
  if (aliasKey && NICHE_SUBREDDITS[aliasKey]) return NICHE_SUBREDDITS[aliasKey];
  for (const key of Object.keys(NICHE_SUBREDDITS)) {
    if (key.includes(q) || q.includes(key)) return NICHE_SUBREDDITS[key];
  }
  return [];
}
